- alias: Write Stepper Value to ESP
  trigger:
    platform: state
    entity_id: input_number.stepper_control
  action:
  - service: esphome.lithophane_lamp_control_stepper
    data_template:
      target: '{{ trigger.to_state.state | int }}'
  id: 6b6f8c80c525426ebcaad405bef0af11
