##########################################################################################
# Home assistant                                                                         #
##########################################################################################
homeassistant:
  name: Thuis
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  country: NL
  customize: !include customize.yaml
  external_url: !secret external_url
  internal_url: !secret internal_url

energy:
my:

##########################################################################################
# Default configuration settings                                                         #
##########################################################################################
default_config:
frontend: # Enables the frontend
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
    - /local/custom.js

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.253

discovery: # Discover some devices automatically
wake_on_lan:
hassio:
api:

lovelace:
  mode: yaml
  resources: !include /config/resources.yaml

# Includes
script: !include scripts.yaml
switch: !include switches.yaml
google_assistant: !include google_assistant.yaml
sensor: !include sensors.yaml
automation: !include automations.yaml
light: !include lights.yaml
template: !include templates.yaml

##########################################################################################
# Media players                                                                          #
##########################################################################################
media_player:
  - platform: onkyo
    name: Onkyo
    host: !secret onkyo_ip
    sources:
      bd-dvd: "Kodi"
      video2: "Ziggo"
      video6: "PC"
      video3: "Xbox"

# Log settings
logger:
  default: error
  logs:
    rflink: debug
    homeassistant.components.rflink: debug

influxdb:
  host: !secret influxdb_ip
  port: !secret influxdb_port
  database: !secret influxdb_database
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

recorder:
  purge_keep_days: 14
  db_url: !secret recorder_db_url
  include:
    domains:
      - sensor
      - binary_sensor
      - light
      - media_player
      - switch
      - climate
    entities:
      - sensor.energy_consumption_tarif_1
      - sensor.energy_consumption_tarif_1_cost
      - sensor.energy_consumption_tarif_2
      - sensor.energy_consumption_tarif_2_cost
      - sensor.dsmr_consumption_gas_delivered
      - sensor.dsmr_consumption_gas_delivered_cost
      - sensor.woonkamer_temperatuursensor_humidity
      - sensor.woonkamer_temperatuursensor_pressure
      - sensor.woonkamer_temperatuursensor_temperature
      - sensor.woonkamer_humidity
      - sensor.woonkamer_temperature

notify:
  - platform: webostv
    host: !secret webos_ip
    name: woonkamer_tv

utility_meter:
  daily_energy_offpeak:
    source: sensor.energy_consumption_tarif_1
    name: Daily Energy (Offpeak)
    cycle: daily
  daily_energy_peak:
    source: sensor.energy_consumption_tarif_2
    name: Daily Energy (Peak)
    cycle: daily
  daily_gas:
    source: sensor.gas_consumption
    name: Daily Gas
    cycle: daily
  monthly_energy_offpeak:
    source: sensor.energy_consumption_tarif_1
    name: Monthly Energy (Offpeak)
    cycle: monthly
  monthly_energy_peak:
    source: sensor.energy_consumption_tarif_2
    name: Monthly Energy (Peak)
    cycle: monthly
  monthly_gas:
    source: sensor.gas_consumption
    name: Monthly Gas
    cycle: monthly

tts:
  - platform: google_translate
    service_name: google_say

rflink:
  port: /dev/ttyACM2

cover:
  - platform: rflink
    devices:
      RTS_0A0A0A_0:
        name: Zonwering tuin

