##########################################################################################
# LED Strips                                                                             #
##########################################################################################
# Hyperion
# - platform: hyperion
  # host: 192.168.178.41
  # port: 19444
  # name: ambilight


# Planfond lamp woonkamer
#- platform: yeelight
#  devices:
#    192.168.20.40:
#      name: Woonkamer plafondlamp
#      transition: 1000
#      save_on_change: True

# - platform: group
#   name: Hong Kong Spots
#   entities:
#     - light.hongkong_spot_1
#     - light.hongkong_spot_2
#     - light.hongkong_spot_3
    
# - platform: group
#   name: Slaapkamer spots
#   entities:
#     - light.slaapkamer_spot_1
#     - light.slaapkamer_spot_2
#     - light.slaapkamer_spot_3
    
# - platform: group
#   name: Keukenverlichting
#   entities:
#     - light.aanrecht_verlichting
#     - light.gasfornuis_verlichting

- platform: group
  name: Werkbank
  entities:
    - light.wled_werkbank_laag
    # - light.wled_werkbank_pegboard_1
    # - light.wled_werkbank_plank